### ISSUE TITLE
Errors while running OdooGenericTaskSet

### ISSUE THREAD

**Issue by tosate** [nseinlet/OdooLocust#9]
Hi @nseinlet

first of all: Thank you for this project!

I am using the `OdooGenericTaskSet` and I am having some trouble with the latest version:

```
[2024-09-03 09:36:28,446] user-vm-ubuntu/ERROR/locust.user.task: 'bool' object has no attribute 'search'
Traceback (most recent call last):
  File "/home/user/git/odoo-ctie/OdooLocust/venv/lib/python3.12/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/home/user/git/odoo-ctie/OdooLocust/venv/lib/python3.12/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/home/user/git/odoo-ctie/OdooLocust/venv/lib/python3.12/site-packages/locust/user/task.py", line 385, in execute_task
    task(self)
  File "/home/user/git/odoo-ctie/OdooLocust/src/OdooLocust/OdooTaskSet.py", line 117, in test_search
    ids = self.model.search(self._get_search_domain(), context=self.client.get_user_context(), limit=80)
          ^^^^^^^^^^^^^^^^^
AttributeError: 'bool' object has no attribute 'search'

[2024-09-03 09:36:29,450] user-vm-ubuntu/ERROR/locust.user.task: 'bool' object has no attribute 'search_count'
Traceback (most recent call last):
  File "/home/user/git/odoo-ctie/OdooLocust/venv/lib/python3.12/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/home/user/git/odoo-ctie/OdooLocust/venv/lib/python3.12/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/home/user/git/odoo-ctie/OdooLocust/venv/lib/python3.12/site-packages/locust/user/task.py", line 385, in execute_task
    task(self)
  File "/home/user/git/odoo-ctie/OdooLocust/src/OdooLocust/OdooTaskSet.py", line 148, in list_view
    nbr_records = self.model.search_count(domain, context=context)
                  ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'bool' object has no attribute 'search_count'
```

As you wrote in your commit message: it's impossible as a regular user to read actions or models through RPC. Nevertheless, the methods `OdooGenericTaskSet.test_search()` and `OdooGenericTaskSet.list_view()` are invoked and since the attribute `OdooGenericTaskSet.model` has never been modified after initialization, it still has the value `False` and so the methods fail.

To prevent this, you could check if `OdooGenericTaskSet.model` has a value other then `False` before you invoke a method of a model object.

However, I don't get how the `OdooGenericTaskSet` should work if `OdooGenericTaskSet.randomlyChooseMenu()` is never invoked and hence `OdooGenericTaskSet.model` is always `False`.

**Comment by nseinlet** [comment]
Hi @tosate , sorry if it's not clear, I will improve this.
The `OdooGenericTaskSet` should be used this way, as the random menu is not working:
```
class Lead(OdooTaskSet.OdooGenericTaskSet):
  model_name = 'crm.lead'
```

Setting the model_name on the taskset will make `on_start` method from `OdooTaskSet` to populate self.model

**Comment by tosate** [comment]
Hi @nseinlet ,

Thank you for the quick response. I can no longer execute the OdooGenericTaskSet directly. Instead, I need to create my own implementation that at least sets the model name, as described in the README.md.

**Comment by nseinlet** [comment]
The read of the actions can only be made by admin. I can either add a record rule for load testing, what I would like to avoid, but still doable, or choose the models this way. Not ideal, I know.
The other way to get the action is to cal;l the backend route, but that one is restricted to authenticated users, and I have no way to perform the 2FA.

Then yes, you're right.

**Comment by tosate** [comment]
Hi @nseinlet 

sorry to bother you again...

I have implemented a test class as defined in your README.md file. There seems to be an issue in the method `OdooGenericTaskSet.list_view`:

```
[2024-09-03 11:01:39,739] qor834-vm-ubuntu/ERROR/locust.user.task: cannot access local variable 'ids' where it is not associated with a value
Traceback (most recent call last):
  File "/home/qor834/git/odoo-ctie/OdooLocust/venv/lib/python3.12/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/home/qor834/git/odoo-ctie/OdooLocust/venv/lib/python3.12/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/home/qor834/git/odoo-ctie/OdooLocust/venv/lib/python3.12/site-packages/locust/user/task.py", line 385, in execute_task
    task(self)
  File "/home/qor834/git/odoo-ctie/OdooLocust/src/OdooLocust/OdooTaskSet.py", line 154, in list_view
    if ids:
       ^^^
UnboundLocalError: cannot access local variable 'ids' where it is not associated with a value
```

The variable `ids` is created if the number of records is greater than 80. If this is not the case, the if statement in line 154 will lead to an error.

In addition, there is another error in `OdooGenericTaskSet.test_websearchread`

```
[2024-09-03 10:59:47,755] qor834-vm-ubuntu/ERROR/locust.user.task: 0
Traceback (most recent call last):
  File "/home/qor834/git/odoo-ctie/OdooLocust/venv/lib/python3.12/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/home/qor834/git/odoo-ctie/OdooLocust/venv/lib/python3.12/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/home/qor834/git/odoo-ctie/OdooLocust/venv/lib/python3.12/site-packages/locust/user/task.py", line 385, in execute_task
    task(self)
  File "/home/qor834/git/odoo-ctie/OdooLocust/src/OdooLocust/OdooTaskSet.py", line 130, in test_websearchread
    self.random_id = res[0]['id']
                     ~~~^^^
KeyError: 0
```

I think you want to access the dictionary value inside res['records'] and from there the element with the key 0. So line 130 should be like: `self.random_id = res['records'][0]['id']`
